name: Android Build (mit OpenCV NDK)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: '29.0.13599879'

      - name: Check NDK path
        run: echo $ANDROID_NDK_HOME
        
      # Build OpenCV native libraries from source
      - name: Fetch OpenCV sources
        run: ./scripts/fetch_opencv.sh

      - name: Build OpenCV native libraries
        run: ./scripts/build_opencv_android.sh

      - name: Prepare OpenCV for app
        run: ./scripts/prepare_opencv.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ENCODED_KEYSTORE" ]; then
            echo "$ENCODED_KEYSTORE" | base64 --decode > app/keystore.jks
            echo "Keystore decoded successfully"
          else
            echo "No keystore provided, will build unsigned APK"
          fi

      - name: Build APK
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release-unsigned.apk