name: Build Release

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag that starts with 'v'

jobs:
  build:
    name: Build APK and AAB
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin distribution
          java-version: '21'
          cache: gradle
          
      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: '29.0.13599879'
          
      - name: Check NDK path
        run: echo $ANDROID_NDK_HOME
        
      # Build OpenCV native libraries from source
      - name: Fetch OpenCV sources
        run: |
          chmod +x scripts/fetch_opencv.sh
          ./scripts/fetch_opencv.sh

      - name: Build OpenCV native libraries
        run: |
          chmod +x scripts/build_opencv_android.sh
          ./scripts/build_opencv_android.sh

      - name: Prepare OpenCV for app
        run: |
          chmod +x scripts/prepare_opencv.sh
          ./scripts/prepare_opencv.sh
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ENCODED_KEYSTORE" ]; then
            echo "$ENCODED_KEYSTORE" | base64 --decode > app/keystore.jks
            echo "Keystore decoded successfully"
          else
            echo "No keystore provided, will build unsigned APK"
          fi
        
      - name: Build debug APK
        run: ./gradlew assembleDebug
        
      - name: Build release APK
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew assembleRelease
        
      - name: Build AAB
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew bundleRelease
        
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
          
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
            app/build/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}